services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel54_app
    volumes:
      - /home/oo1/Documents/itforms:/var/www
    working_dir: /var/www
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: php artisan serve --host=0.0.0.0 --port=8000

  db:
    image: mysql:5.7
    container_name: laravel54_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
